_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
            "3":
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": linux-x86_64
